novorender/novoweb

.github/workflows/azure.yml, .github/workflows/deploy-explorer.yml, .gitignore, infrastructure/explorer.bicep, infrastructure/modules/nodeWebApp.bicep, infrastructure/modules/webAppAccessPolicy.bicep, infrastructure/modules/webAppSettings.bicep
Added infrastructre as code. 
Added deployment pipeline to new environment.
Shouldn't impact existing resources in any way.
=> New test environment

src/apis/dataV2/omega365Types.ts, src/features/omega365/omega365.tsx
https://trello.com/c/wLjVtU02/718-omega-add-a-link-to-object-details-page
External link is hardcoded for now.
=> Omega365: add Object details link to component header

src/features/deviations/deviations.tsx
Fix for Rafa comment on https://trello.com/c/5jr3rH5R/719-create-new-diviations-profiles-frontedn-and-backend-for-storage-of-the-profiles
Also lock all widget menu buttons when editing a deviation
=> Fix route for adding a deviation

src/apis/dataV2/dataV2Api.ts, src/apis/dataV2/projectTypes.ts, src/features/advancedSettings/routes/projectSettings.tsx, src/features/arcgis/hooks/useProjectEpsg.ts, src/features/ditio/hooks/useDitioFeedMarkers.ts, src/features/ditio/hooks/useDitioMachineMarkers.ts, src/features/ditio/routes/feed/post.tsx, src/features/images/routes/root.tsx, src/features/myLocation/myLocation.tsx, src/features/myLocation/useHandleLocationMarker.ts, src/features/render/hooks/useHandleInit.ts, src/features/render/renderSlice.ts, src/features/xsiteManage/hooks/useHandleXsiteManageMachineLocations.ts, src/slices/explorerSlice.ts, src/utils/misc.ts
https://trello.com/c/BXHlOwxM/735-explorer-doesnt-show-tm-zone-defined-in-projects
- Show EPSG next to zone name
- In v2 projects disable dropdown, show zone from project v2 info and add link to Projects
- Move zoneNameToEpsg from arcgis to shared utils
=> Update TM Zone dropdown

src/features/images/useHandleImages.ts
https://trello.com/c/GFmUoL85/767-panorama-cant-see-image
When going out of panorama mode - set near back to camera default. The issue is that if user configured near to >=1 - he won't see anything in panorama mode.
=> Panorama: force near plane to 0.1 when going to panorama mode

src/features/bookmarks/routes/bookmarkList.tsx
https://trello.com/c/I4oIS5Q9/768-bookmarks-dont-save-public-bookmarks-if-not-admin
=> Bookmarks: don't save public bookmarks if you're viewer

src/features/groups/collection.tsx
https://trello.com/c/1cri4Urd/779-groups-fix-nested-collection-prefix
=> Groups: use proper prefix for nested groups

src/features/deviations/hooks/useHighlightDeviation.ts, src/features/deviations/hooks/useSaveDeviationConfig.ts, src/features/deviations/utils.ts
https://trello.com/c/yUPJEUjX/780-deviations-always-fetch-group-ids-in-usehighlightdeviations
=> Deviations: useDeviationsHighlight should always prefetch groups object IDs

src/features/deviations/deviationsSlice.ts, src/features/deviations/selectors.ts, src/features/followPath/followHtmlInteractions.tsx, src/features/measure/canvas.tsx, src/utils/math.ts
https://trello.com/c/vUug6tKD/781-deviations-better-placement-for-the-legend-in-3d
- Instead of floating legend attaching to the centerline point closest to camera it's now looking for a point closest to screen center
- Legend changes attachment point left/right top/bottom depending on where it is on the screen
=> Deviations legend better placement

package-lock.json, package.json
https://trello.com/c/A2H4Tj52/782-measure-lazy-resolve-id-hash
=> Update novorender/api to 0.1.29

src/dataApi.d.ts, src/features/arcgis/arcgisSlice.ts, src/features/bookmarks/useCreateBookmark.ts
https://trello.com/c/R7XcJHxO/792-arcgis-support-bookmarks
=> Arcgis: support bookmarks

src/features/deviations/hooks/useCalcDeviations.ts
https://trello.com/c/2HQAZJEs/799-deviations-calcdeviations-is-called-with-rebuildrequiredfalse
=> Deviations: always set rebuildRequired=true for /calcdeviations

src/features/myLocation/myLocation.tsx, src/features/myLocation/myLocationMarker.tsx, src/features/myLocation/myLocationSlice.ts, src/features/myLocation/useGoToMyLocation.ts, src/features/myLocation/useHandleLocationMarker.ts, src/features/render/hooks/useCanvasEventHandlers.ts, src/features/render/hooks/useHandleCameraState.ts
https://trello.com/c/bQ3F3Pb5/807-my-location-center-camera-on-marker
- Change marker for my location to the same as google maps have
- New "Center" option to automatically center on the marker
- Only show marker when "Marker" is enabled
- Support flyTime for ortho camera
- Chnage location min update rate 5000->500ms
=> My location auto center

src/contexts/highlightCollections/reducer.ts, src/features/forms/api.ts, src/features/forms/routes/instance/searchInstance.tsx, src/features/forms/utils.ts
[Card](https://trello.com/c/FV5kd1EP/1372-vassbakk-the-status-of-forms-does-not-change-colours-of-objects-correctly).
=> Forms: update individual object highlighting

src/features/groups/routes/crupdate/createJsonGroup.tsx
https://trello.com/c/yjHTp6MM/793-update-searchpattern-link-in-group-input-json
=> Fix link to SearchPattern docs in groups input JSON

src/features/properties/routes/root.tsx
https://trello.com/c/1NJiGngb/811-properties-limit-to-200-properties-max
Show warning when some properties are hidden
=> Limit property widget to showing 200 properties (own and parent combined)

package-lock.json, package.json, src/features/flyToSelected/flyToSelected.tsx, src/utils/math.ts
https://trello.com/c/Ns66jI24/813-fly-to-2d-switches-to-3d
=> Fly to: stay in ortho when in 2d mode

src/features/advancedSettings/routes/featureSettings.tsx, src/features/render/renderSlice.ts
[Card](https://trello.com/c/c60eU6aR)
=> Add generated parametric data toggle

src/config/features.tsx, src/features/advancedSettings/routes/featureSettings.tsx
https://trello.com/c/HVenmMYZ/834-clash-move-checkbox-to-enable-widget-into-beta-section
=> Move beta widgets into Beta section

src/utils/objectData.ts
https://trello.com/c/ajE09xIh/835-show-proper-path-for-laz-files
=> Recognize laz extension

src/features/render/canvasContextMenuStamp/stamp.tsx, src/utils/objectData.ts
[Card](https://trello.com/c/QixSNVyt).
=> Load centerLine and measureEntity concurrently

server.mjs
https://trello.com/c/PFVleuJ3/840-newform-konekt-widget-not-loading
=> server.mjs: remove trailing slashes from paths in proxy

package-lock.json, package.json, src/features/measure/measuredObject.tsx
https://trello.com/c/1xGWjwW8/837-show-error-margin-of-generated-planes
=> Show error margin of generated plane

src/features/advancedSettings/routes/performanceSettings.tsx
https://trello.com/c/6jxYKers/846-add-tier-selector-in-perf-settings-in-debug-mode
=> Add device tier selector in debug mode

src/features/offline/useHandleOffline.ts
https://trello.com/c/cZybJytX/847-offline-fix-initialization-race
=> Fix race (view.renderState.scene.config.id) in offline init

src/features/forms/utils.ts, src/utils/time.ts
[Card](https://trello.com/c/sShTjk6I)
=> Forms: Add toLocalISOString to save local time offset

src/features/ditio/hooks/useDitioMachineMarkers.ts
https://trello.com/c/vWJdXV2j/858-ditio-dont-crash-when-failing-to-get-marker-positions
=> Don't crash when latLon2tm fails inside Ditio markers

src/features/render/hooks/useHandleInit.ts, src/features/render/utils.ts, vite.config.ts
So try WKT and if it fails - use proj4
https://trello.com/b/Ub3JRyEl/novorender-frontend
=> Coord conversion: sometimes WKT doesn't work, sometimes proj4 string doesn't work

src/features/render/hooks/useCanvasEventHandlers.ts, src/features/render/hooks/useHandleInit.ts
https://trello.com/c/BjEU33uj/861-dont-move-camera-on-moving-clipping-plane-with-shift
=> Prevent zooming when moving clipping with shift+wheel

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/fr/translation.json, public/locales/no/translation.json, src/dataApi.d.ts, src/features/clippingPlanes/clippingPlaneInteractions.tsx, src/features/clippingPlanes/useClippingPlaneActions.ts, src/features/clippingPlanes/useHandleClipping.ts, src/features/render/canvasContextMenuStamp/stamp.tsx, src/features/render/hooks/useCanvasClickHandler.ts, src/features/render/renderSlice.ts
- Included into bookmark
- Disabled by default
- Per plane
https://trello.com/c/1i1Cw1P3/864-clipping-plane-option-to-show-hide-plane-disabled-by-default
=> Option to show/hide clipping plane itself (color)

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/fr/translation.json, public/locales/no/translation.json, src/features/shareLink/shareLink.tsx, src/features/widgetGroupPanel/widgetGroupPanel.tsx
https://trello.com/c/hlb8dZ0K/865-new-ux-share-link-doesnt-work-from-right-menu
=> Fix share link behavior when called from right sidebar menu

src/features/render/hooks/useCanvasEventHandlers.ts
Otherwise camera Z moving with Shift+Wheel doesn't work
https://trello.com/c/lJf7pNLA/866-zoom-with-shift-pressed-in-ortho-doesnt-move-z
=> Set disableWheelOnShift for view controller to false on Shift in ortho camera

src/features/forms/forms.tsx, src/features/forms/hooks/useGoToSelectedForm.ts, src/features/forms/routes/formsList/formsListItem.tsx, src/features/forms/routes/instance/locationInstance.tsx, src/features/forms/routes/instance/searchInstance.tsx, src/features/forms/routes/object.tsx
Forms should properly load for objects with arbitrary (non IFC-compliant) GUIDs.
[Card.](https://trello.com/c/NbS7YU1z)
=> Forms: Fix forms for objects with arbitrary guids

src/features/render/hooks/useCanvasEventHandlers.ts
https://trello.com/c/e77cHNXT/871-shifting-z-plane-shouldnt-require-canvas-to-be-focused
=> Attach Shift tracker to window instead of canvas so user don't have to focus canvas first

src/features/render/sceneError/sceneError.tsx
https://trello.com/c/q2XJznhv/867-missing-translation
=> Fix minor scene error i18n issues

src/features/forms/api.ts
* Optimistic update of location form counters (FE)
* Fix final location forms statuses changed on template update (BE)
=> Forms: Update location template count

src/features/render/canvasContextMenuStamp/stamp.tsx
https://trello.com/c/bSrgzuwS/886-adding-clipping-plane-from-context-menu-doesnt-work-in-offline-or-when-search-is-down
=> Don't crash when creating a clipping plane while offline

src/features/forms/routes/formsList/formsList.tsx
[Card](https://trello.com/c/cMZQ3R0w).
=> Set SemiTransparent as the default visibility for object forms

src/features/groupedWidgetList/routes/root.tsx, src/features/widgetGroupPanel/widgetGroupPanel.tsx
https://trello.com/b/Ub3JRyEl/novorender-frontend
=> Remove share link from widget list as well

src/features/quickAccessMenu/quickAccessMenu.tsx
- Also add Cross section to clipping menu
https://trello.com/c/W3uCddjD/907-new-ux-left-bar-close-measure-picker-by-clicking-on-category-button-in-left-menu
=> Change left bar behavior for measure and clipping sections.

src/features/forms/routes/formsList/formsList.tsx
[Card](https://trello.com/c/eaZmgiuB/1673-bg-geoforms-makes-weird-colors-all-over-the-screen)
=> Skip highlight in geo forms list

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/fr/translation.json, public/locales/no/translation.json, src/contexts/objectGroups/reducer.ts, src/features/groups/collection.tsx, src/features/groups/group.tsx, src/features/groups/groups.tsx, src/features/groups/groupsSlice.ts, src/features/groups/routes/delete.tsx, src/features/groups/routes/groupList.tsx
https://trello.com/c/vxo0WI4q/906-delete-multiple-groups
=> Delete multiple groups

src/features/images/imageListItem.tsx, src/features/images/imageMarkers.tsx, src/features/images/useHandleImages.ts
- Also add FLAT button to pano image list items
https://trello.com/c/BWR3qTgt/905-make-panorama-360-image-view-as-default
=> Open pano images in pano mode by default

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/fr/translation.json, public/locales/no/translation.json, src/contexts/objectGroups/reducer.ts, src/features/arcgis/components/canvas.tsx, src/features/crossSection/clipping2d.tsx, src/features/engine2D/utils.ts, src/features/followPath/canvas.tsx, src/features/followPath/follow.tsx, src/features/followPath/followPathSlice.ts, src/features/followPath/types.ts, src/features/followPath/useCrossSection.ts, src/features/groups/collection.tsx, src/features/groups/group.tsx, src/features/groups/groups.tsx, src/features/groups/groupsSlice.ts, src/features/groups/routes/delete.tsx, src/features/groups/routes/groupList.tsx, src/features/images/imageListItem.tsx, src/features/images/imageMarkers.tsx, src/features/images/useHandleImages.ts, src/features/outlineLaser/canvas.tsx, src/features/pointLine/canvas.tsx
=> Road layers and tracer on general roads

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/fr/translation.json, public/locales/no/translation.json, src/features/forms/hooks/useObjectProperty.ts, src/features/forms/routes/create/addFormItem.tsx, src/features/forms/routes/create/index.tsx, src/features/forms/routes/instance/formItem.tsx, src/features/forms/types.ts, src/features/forms/utils.ts, src/utils/search.ts
[Card](https://trello.com/c/9M237R3M)
=> Forms: Add ability to derive input and text fields from properties

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/fr/translation.json, public/locales/no/translation.json, src/features/followPath/canvas.tsx, src/features/followPath/follow.tsx, src/features/followPath/hooks/useIsCameraAlignedWithClippingPlane.ts
- Fix styling for radio group
- Hide radio group and disable functionality when not in 2D or when camera is not aligned with clipping plane
https://trello.com/c/9oz5gNVM/914-slope-and-filter-on-outline-drawings
=> Centerline tracer:

src/features/followPath/canvas.tsx, src/features/followPath/follow.tsx, src/features/followPath/followPathSlice.ts, src/features/followPath/useCrossSection.ts
- Hide section when there is no data for tracer
- Fix search path
https://trello.com/c/9oz5gNVM/914-slope-and-filter-on-outline-drawings
=> Centerline tracer fixes
