src/features/forms/formFilterMenu.tsx, src/features/forms/routes/templates/template.tsx, src/features/forms/slice.tsx, src/features/forms/templateFilterMenu.tsx
* Change "Search" prompts in filters to "Search by name"
* Use form icons inside form type filter (template screen), same icons as in the filter itself
* Form types in filters and template creation don't match
* In form status filter - add colored status dot to the filter, same as the forms have
Backend fix (not in this PR):
- New geo forms have In Progress status by default
[Task](https://trello.com/c/hBCdLw9e/746-forms-small-improvements)
=> Small Forms improvements

src/dataApi.d.ts, src/features/bookmarks/useCreateBookmark.ts, src/features/deviations/components/groupsAndColorsHud.tsx, src/features/deviations/components/subprofileSelect.tsx, src/features/deviations/components/viewSwitchSection.tsx, src/features/deviations/deviationTypes.ts, src/features/deviations/deviations.tsx, src/features/deviations/deviationsSlice.ts, src/features/deviations/hooks/useHighlightDeviation.ts, src/features/deviations/hooks/useMergeFormAndSave.ts, src/features/deviations/hooks/useSetCenterLineFollowPath.ts, src/features/deviations/routes/root.tsx, src/features/deviations/useHandleDeviations.ts, src/features/followPath/canvas.tsx, src/features/followPath/follow.tsx, src/features/followPath/followHtmlInteractions.tsx, src/features/home/useResetView.ts, src/features/render/hooks/useCanvasClickHandler.ts, src/features/render/hooks/useCanvasEventHandlers.ts, src/features/render/hooks/useHandleHighlights.ts, src/features/render/renderSlice.ts, src/types/misc.ts
https://trello.com/c/EA1Lnwd6/761-deviations-support-bookmarks
- Info we save is profile ID, subprofile index, active and hidden groups
- Changed storage mechanism for hidden groups because of that
- Instead of "active" flag in deviations use ViewMode.Deviations. Most FollowPath functionality works in this mode as well
- When doing actions inside Deviations root view - set view mode to Deviations in case somebody did reset view before
- Better support for reset view
- Group list is always shown in Deviations root when subprofile doesn't have a center line
=> Deviations now support bookmarks

src/features/clippingPlanes/planes.tsx
https://trello.com/c/odHf3xP5/770-clipping-planes-dont-render-outlines-when-moving-sliders
=> Clipping planes: don't render outlines when moving sliders

src/features/forms/routes/formsList/formsList.tsx, src/features/forms/routes/instance/locationInstance.tsx
Entering the object form should make other objects transparent. Otherwise object might be not noticeable enough, e.g. when flying to it and there's smth between camera and the object.
[CARD](https://trello.com/c/hBCdLw9e)
=> Set visibility to semiTransparent when geo form is open or added

src/features/arcgis/hooks/useLoadFeaturesAndDefinition.ts
https://trello.com/c/TR6IbGtA/777-arcgis-use-objectidfield-instead-of-hardcoded-objectid
=> ArcGIS: use `objectIdField` instead of hardcoded "OBJECTID"

src/features/deviations/components/subprofileList.tsx, src/features/deviations/deviations.tsx, src/features/deviations/routes/deviation.tsx, src/features/deviations/useHandleDeviations.ts, src/features/followPath/canvas.tsx, src/features/followPath/followPathSlice.ts, src/features/followPath/hooks/useLoadLandXmlPath.ts, src/features/followPath/types.ts, src/utils/manualCache.ts, vite.config.ts
https://trello.com/c/VOTBFW0n/753-offilne-improvements-when-device-is-out-of-disk-space
- Deviations and project v2 info are cached by vite-pwa
- Follow paths are cached manually because it's easier to cache search result this way
- brep ID is loaded together with main land XML fetches now
- Deviation widget disables things properly when offline
=> Deviations and follow path are available offline

src/features/advancedSettings/advancedSettings.tsx
https://trello.com/c/pbBfMbBa/784-adv-settings-dont-overwrite-properties
Properties settings are updated in "Properties" widget, so it doesn't really make sense to update them here. People end up overwriting other people changes more often.
=> Adv. Settings - use latest server settings for `properties`

src/features/arcgis/routes/editFeatureServer.tsx
https://trello.com/c/2x9MmbAS/783-arcgis-forbid-adding-sceneserver
People were trying to add SceneServer and it was valid because response has `layers` field.
=> ArcGIS: require feature server URL to end with FeatureServer (plus optional layer ID)

src/features/forms/routes/instance/formItem.tsx
Display "richer" version of input while it's not edited.
Basically, draw a text element (with links) while the user is not inputting anything.
=> Forms: Add editing mode to the input form field

package-lock.json, package.json, src/features/propertyTree/api.ts
https://trello.com/c/v8grLwFv/785-property-tree-use-md5-hash-for-long-blob-names
=> Property tree: if path is over 128 length - md5 it when making a request

src/features/followPath/canvas.tsx, src/features/followPath/follow.tsx, src/features/followPath/followInteractions.tsx
https://trello.com/c/XoKeE9Jn/749-follow-path-enable-disable-on-screen-controls-when-the-widget-is-closed
=> Feature/add follow path on-screen close button

src/features/deviations/components/groupsAndColorsHud.tsx, src/features/deviations/hooks/useHighlightDeviation.ts, src/features/deviations/hooks/useSetCenterLineFollowPath.ts, src/features/deviations/selectors.ts, src/features/followPath/followHtmlInteractions.tsx
https://trello.com/c/xDt16wuJ/786-deviations-legend-should-only-contain-favourite-groups
Deviations legend used to show combination of groups to analyse, analyse against and legend groups. Instead we only need to show legend groups, so if groups to analyse/analyse against are not listed in legend groups - they can't be hidden.
In addition fixed an issue where we change view mode to default for profiles without center line and it changes visibility mode to default and we see more than we should.
=> Deviations: only show legend groups in legend

src/features/properties/routes/root.tsx
https://trello.com/c/bEwPCVuK/795-properties-dont-limit-property-count
For some reason Properties widget only shows 100 properties and 50 parent properties. Because of this users don't see some properties they'd like to see. Noone knows why and commit/trello history doesn't show enough details.
=> Properties: don't limit property count

src/features/home/useResetView.ts, src/features/render/hooks/useDefaultCamera.ts, src/features/render/hooks/useHandleInit.ts, src/features/render/renderSlice.ts, src/features/render/utils.ts
If there is no initial camera in the scene,
set the default camera based on the Project's bounding box with a default "side"perspective.
Fixes [this card](https://trello.com/c/FYF8RO4b).
Test scenes:
[Customer's scene](https://explorer.novorender.com/4922df9a36de45218654115bd773a0da) (camera set by customer)
[Test scene](https://explorer.novorender.com/af41085a8ae74f558d1f5f25f9c264ce) (same scene, no preset camera)
=> Render: set default camera based on the project bounds

src/features/forms/routes/instance/formItem.tsx
Fix focus when changing location form name (Input field related).
Also fixes a couple of "dead" states when user clears the input and can no longer change it due to Input form field rendering as "empty text field" that is impossible to click.
[Card.](https://trello.com/c/hgZMOaF3)
=> Fix focus when changing location form name

src/features/advancedSettings/advancedSettings.tsx, src/features/properties/slice.ts, src/features/render/renderSlice.ts, src/features/render/utils.ts, src/slices/explorer/slice.ts, src/types/project.ts
https://trello.com/c/RhbOtt4X/805-project-with-only-copied-starred-properties-more-granular-check-for-explorer-settings-during-init
Project https://explorer.novorender.com/1108dcdda6c64cd987807d1085fdc536 should open
Currently in app init check for explorer settings is not granular - if explorer settings are presented - we assume that everything inside is also presented. But with new projects functionality people can create a new project and only copy few settings to it, so we have to check for specific properties inside explorer settings when initializing.
=> More granular explorer settings check in init

src/features/forms/routes/create/addObjects.tsx
Fixes [this](https://trello.com/c/sYMNtEgI/1360-fob-cannot-create-forms-for-ifc-file) sales ops ticket.
They want to create forms for **2873** objects.
This is currently above our threshold of 2k.
I bumped threshold to **5k** as we're confident enough we can handle this amount (with some waiting times for the search).
This is definitely better than not being able to create forms in the first place.
=> Forms: Bump max objects count to 5k

src/components/confirmation.tsx, src/components/imgModal.tsx, src/features/forms/addFilesButton.tsx, src/features/forms/api.ts, src/features/forms/constants.ts, src/features/forms/routes/create/addFormItem.tsx, src/features/forms/routes/instance/formItem.tsx, src/features/forms/routes/instance/formItems/fileItem.tsx, src/features/forms/routes/instance/locationInstance.tsx, src/features/forms/routes/instance/searchInstance.tsx, src/features/forms/types.ts, src/features/forms/utils.ts
* Add support for uploading files to forms
User can add file item to the form. Files can be uploaded either at form creation stage or when form instance is filled by the user.
* Forms display rich element with previews for images & PDFs.
* Form creation dialog is updated to reflect growing number of items' types that are supported.
=> Forms: support for files upload

src/utils/search.ts
https://trello.com/c/cgB7Dnp1/845-dbdescendants-can-return-nans
=> Filter out NaN descendants

src/features/render/hooks/useHandleInit.ts
If we pass near/far plane - it will mess things up when changing near/far plane in adv. settings (values will keep reset to whatever was passed in `initialCamera`)
https://trello.com/c/PQVTJyhl/852-camera-near-far-plane-resets-after-changing-it
=> When initializing camera from `view.renderState.camera` - pass only expected attributes

src/features/images/imageMarkers.tsx
https://trello.com/c/A9Oa1BQr/872-images-guid-is-not-reliably-unique-to-be-used-as-key
=> Don't use image guid as key for image markers because it might be not unique

src/components/widgetHeader.tsx, src/features/clippingPlanes/clippingPlaneInteractions.tsx, src/features/followPath/followInteractions.tsx, src/features/forms/formsTopDown.tsx, src/features/forms/hooks/useLocationFormAssetClickHandler.ts, src/features/groupedWidgetList/groupedWidgetList.tsx, src/features/measure/measureInteractions.tsx, src/features/pointVisualization/pointVisualization.tsx, src/features/propertyTree/propertyTree.tsx, src/features/widgetList/widgetList.tsx, src/features/widgets/widgets.tsx, src/hooks/useOpenWidget.ts, src/hooks/useRemoveWidget.ts
https://trello.com/c/9Qd0122a/900-mixpanel-widget-events-are-not-sent-in-new-ux-and-in-some-other-cases
Add/patched hooks `useOpenWidget` and `useRemoveWidget`
- `useOpenWidget` should be used instead of `addWidgetSlot`, `forceOpenWidget`, `replaceWidgetSlot`
- `useRemoveWidget` should be used instead of `removeWidgetSlot`
Using hooks ensures proper mixpanel reporting of "Opened Widget" and "Closed Widget" event
=> Add hooks to open/replace/close widgets to have consistent mixpanel reporting

src/features/globalSearch/globalSearch.tsx
https://trello.com/c/wLsMFfvp/903-global-search
Solution is to simulate click on the overlay so popup closes.
Only other solution that was working is to hide popup temporarily which looks a bit weird.
=> Global search: close any currently open menu to fix input focus
